# Generated by Django 3.2.12 on 2022-11-21 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.TextField(blank=True, default='https://assets.repress.co.kr/photos/2009ea104d2c842fed5461308d9f92d7/original.jpg'),
        ),
    ]
